[package]
name = "destream_json"
version = "0.8.4"
authors = ["haydn@tinychain.net"]
edition = "2018"
license = "Apache-2.0"
description = "Library for decoding & encoding a JSON stream"
repository = "https://github.com/haydnv/destream_json"
readme = "README.md"

categories = ["asynchronous", "encoding", "parser-implementations", "parsing", "web-programming"]
keywords = ["json", "stream", "serialize", "deserialize"]

[features]
default = []
tokio-io = ["tokio/io-util"]
value = ["number-general"]
all = ["tokio-io", "value"]

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = { version = "1.0", features=["serde"] }
destream = "0.5"
futures = "0.3"
number-general = { version = "0.3", optional = true }
pin-project = "1.0"
tokio = { version = "1.9", features = ["io-util"], optional = true }
async-stream = "0.3.2"
futures-util = "0.3.16"
serde = "1"

[dev-dependencies]
number-general = "~0.3.9"
tokio = { version = "1.11", features = ["fs", "macros"] }
tokio-util = { version = "0.6", features = ["io"] }
tokio-test = "0.4"
