apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: big-brother
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: big-brother
rules:
  - verbs: ['get', 'list', 'watch']
    apiGroups: ['*']
    resources: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: big-brother
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: big-brother
subjects:
- kind: ServiceAccount
  name: big-brother
  namespace: {{ .Release.Namespace }}
